### ISSUE TITLE
Java error "The element type meta must be terminated by matching end-tag

### ISSUE THREAD

**Issue by nobleach** [amardaxini/acts_as_flying_saucer#1]
I'm running this gem in a new rails 3.0.6 project. When I attempt to render a PDF, my log fills with errors like:

ERROR:  'The element type "meta" must be terminated by the matching end-tag "</meta>".'
Exception in thread "main" org.xhtmlrenderer.util.XRRuntimeException: Can't load the XML resource (using TRaX transformer). org.xml.sax.SAXParseException; lineNumber: 15; columnNumber: 3; The element type "meta" must be terminated by the matching end-tag "</meta>".
    at org.xhtmlrenderer.resource.XMLResource$XMLResourceBuilder.createXMLResource(XMLResource.java:191)
    at org.xhtmlrenderer.resource.XMLResource.load(XMLResource.java:71)
    at org.xhtmlrenderer.swing.NaiveUserAgent.getXMLResource(NaiveUserAgent.java:211)
    at org.xhtmlrenderer.pdf.ITextRenderer.loadDocument(ITextRenderer.java:134)
    at org.xhtmlrenderer.pdf.ITextRenderer.setDocument(ITextRenderer.java:138)
    at acts_as_flying_saucer.Xhtml2Pdf.main(Xhtml2Pdf.java:25)
Caused by: javax.xml.transform.TransformerException: org.xml.sax.SAXParseException; lineNumber: 15; columnNumber: 3; The element type "meta" must be terminated by the matching end-tag "</meta>".
    at com.sun.org.apache.xalan.internal.xsltc.trax.TransformerImpl.transform(TransformerImpl.java:723)
    at com.sun.org.apache.xalan.internal.xsltc.trax.TransformerImpl.transform(TransformerImpl.java:317)
    at org.xhtmlrenderer.resource.XMLResource$XMLResourceBuilder.createXMLResource(XMLResource.java:189)
    ... 5 more
Caused by: org.xml.sax.SAXParseException; lineNumber: 15; columnNumber: 3; The element type "meta" must be terminated by the matching end-tag "</meta>".
    at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1234)
    at com.sun.org.apache.xalan.internal.xsltc.trax.TransformerImpl.transformIdentity(TransformerImpl.java:640)
    at com.sun.org.apache.xalan.internal.xsltc.trax.TransformerImpl.transform(TransformerImpl.java:711)
    ... 7 more

The file size of the resulting PDF is 0 Bytes. (because it's not actually rendering)

I'm running on Ubuntu Linux (10.10) I have the latest Sun Java JDK installed.

Thanks for any direction.

**Comment by nobleach** [comment]
After a bit of fumbling around, I found a couple of things. 1. PROPER XHTML is key. I write HTML5 so my <br> tags need to be xhtml style <br /> tags. That was enough to trip up the renderer. Another thing of importance. A layout file is semi-important. The examples don't specify that it's necessary to use a :layout => 'name_of_layout.html.erb' in your controller action. I couldn't get it to work otherwise. You can do :layout => false if you just want barebones text. Including stylesheets would require you have a head to your document... I found it easier to create a layout. (XHTML compatible here too!)
