### ISSUE TITLE
Non-inlined CSS files not working?

### ISSUE THREAD

**Issue by bratsche** [amardaxini/acts_as_flying_saucer#3]
Hi, I just setup a Rails 3 project using acts_as_flying_saucer and everything appears to be working just fine except that I can't seem to include an external CSS file using stylesheet_link_tag in the <head>.  I'm trying to do:

<%= stylesheet_link_tag 'compiled/pdf.css', :media => 'print' %>

pdf.css is generated by Sass, but in an effort to just get bootstrapped it's super simple and is only generating the following code:

div.red {
  background-color: red;
}

The CSS file is being correctly generated by Sass, and appears as you see above.  When I fetch the PDF file from Rails I get the following stack trace:

java.io.IOException: Stream closed
    at java.io.BufferedInputStream.getInIfOpen(BufferedInputStream.java:134)
    at java.io.BufferedInputStream.read1(BufferedInputStream.java:256)
    at java.io.BufferedInputStream.read(BufferedInputStream.java:317)
    at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:264)
    at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:306)
    at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:158)
    at java.io.InputStreamReader.read(InputStreamReader.java:167)
    at org.xhtmlrenderer.css.parser.Lexer.zzRefill(Lexer.java:1634)
    at org.xhtmlrenderer.css.parser.Lexer.yylex(Lexer.java:1865)
    at org.xhtmlrenderer.css.parser.CSSParser.next(CSSParser.java:1798)
    at org.xhtmlrenderer.css.parser.CSSParser.la(CSSParser.java:1810)
    at org.xhtmlrenderer.css.parser.CSSParser.stylesheet(CSSParser.java:159)
    at org.xhtmlrenderer.css.parser.CSSParser.parseStylesheet(CSSParser.java:89)
    at org.xhtmlrenderer.context.StylesheetFactoryImpl.parse(StylesheetFactoryImpl.java:78)
    at org.xhtmlrenderer.context.StylesheetFactoryImpl.parse(StylesheetFactoryImpl.java:95)
    at org.xhtmlrenderer.context.StylesheetFactoryImpl.getStylesheet(StylesheetFactoryImpl.java:174)
    at org.xhtmlrenderer.context.StyleReference.readAndParseAll(StyleReference.java:123)
    at org.xhtmlrenderer.context.StyleReference.setDocumentContext(StyleReference.java:107)
    at org.xhtmlrenderer.pdf.ITextRenderer.setDocument(ITextRenderer.java:175)
    at org.xhtmlrenderer.pdf.ITextRenderer.setDocument(ITextRenderer.java:142)
    at org.xhtmlrenderer.pdf.ITextRenderer.setDocument(ITextRenderer.java:138)
    at acts_as_flying_saucer.Xhtml2Pdf.main(Xhtml2Pdf.java:25)

I see stylesheet-related stack frames.  And the code works fine if I inline it into the HTML.  It's only when it's linked from the view that it fails.

Do you have some idea of how to fix this, or is it fixable?  I can just inline it in to the HTML view if I need to, but I'd rather keep it external so I can style with Sass.

**Comment by amardaxini** [comment]
Hi,Can you try with :media=>all,and first set debug is true and check whether html is generated properly.Then try to generate PDF.I am also facing this issue for one project I think CSS is not loaded when PDF is generated. I will find out solution as early as possible.

**Comment by amardaxini** [comment]
Hi,
This issue can be solved  by adding
`config.action_controller.asset_host = "http://domain.com"` into respective environment file.

**Comment by amardaxini** [comment]
In 0.0.8 version issue is fixed.

**Comment by amardaxini** [comment]
Kindly refer,
http://jguimont.com/post/2627758108/pdfkit-and-its-middleware-on-heroku
https://github.com/pdfkit/pdfkit/issues/110
