### ISSUE TITLE
Java-ERROR:  'The entity "nbsp" was referenced, but not declared.'

### ISSUE THREAD

**Issue by kurianm** [amardaxini/acts_as_flying_saucer#4]
Hi Amar,

```
 i am trying to use the acts_as_flying_saucer in a rails 3.0.7. When i am trying to generate i gets the following error. Please guide me how to use it. 
```

ERROR:  'The entity "nbsp" was referenced, but not declared.'
Exception in thread "main" org.xhtmlrenderer.util.XRRuntimeException: Can't load the XML resource (using TRaX transformer). org.xml.sax.SAXParseException; lineNumber: 35; columnNumber: 169; The entity "nbsp" was referenced, but not declared.
    at org.xhtmlrenderer.resource.XMLResource$XMLResourceBuilder.createXMLResource(XMLResource.java:191)
    at org.xhtmlrenderer.resource.XMLResource.load(XMLResource.java:71)
    at org.xhtmlrenderer.swing.NaiveUserAgent.getXMLResource(NaiveUserAgent.java:212)
    at org.xhtmlrenderer.pdf.ITextRenderer.loadDocument(ITextRenderer.java:137)
    at org.xhtmlrenderer.pdf.ITextRenderer.setDocument(ITextRenderer.java:141)
    at acts_as_flying_saucer.Xhtml2Pdf.main(Xhtml2Pdf.java:16)
Caused by: javax.xml.transform.TransformerException: org.xml.sax.SAXParseException; lineNumber: 35; columnNumber: 169; The entity "nbsp" was referenced, but not declared.
    at com.sun.org.apache.xalan.internal.xsltc.trax.TransformerImpl.transform(TransformerImpl.java:723)
    at com.sun.org.apache.xalan.internal.xsltc.trax.TransformerImpl.transform(TransformerImpl.java:317)
    at org.xhtmlrenderer.resource.XMLResource$XMLResourceBuilder.createXMLResource(XMLResource.java:189)
    ... 5 more
Caused by: org.xml.sax.SAXParseException; lineNumber: 35; columnNumber: 169; The entity "nbsp" was referenced, but not declared.
    at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1234)
    at com.sun.org.apache.xalan.internal.xsltc.trax.TransformerImpl.transformIdentity(TransformerImpl.java:640)
    at com.sun.org.apache.xalan.internal.xsltc.trax.TransformerImpl.transform(TransformerImpl.java:711)
    ... 7 more

**Comment by amardaxini** [comment]
Hi
You are using which version of gem.Use latest gem
Try clean=>true parameter when you are generating PDF, it requires a tidy
library.
More info regarding new features that are avail in library you can find
http://railstech.com/2011/10/walk-through-of-new-features-of-acts_as_flying_saucer-xhtml-to-pdf/

On Mon, Jan 23, 2012 at 1:29 PM, kurianm <
reply@reply.github.com

> wrote:
> 
> Hi Amar,
> 
> ```
> i am trying to use the acts_as_flying_saucer in a rails 3.0.7. When i
> ```
> 
> am trying to generate i gets the following error. Please guide me how to
> use it.
> ERROR:  'The entity "nbsp" was referenced, but not declared.'
> Exception in thread "main" org.xhtmlrenderer.util.XRRuntimeException:
> Can't load the XML resource (using TRaX transformer).
> org.xml.sax.SAXParseException; lineNumber: 35; columnNumber: 169; The
> entity "nbsp" was referenced, but not declared.
>        at
> org.xhtmlrenderer.resource.XMLResource$XMLResourceBuilder.createXMLResource(XMLResource.java:191)
>        at org.xhtmlrenderer.resource.XMLResource.load(XMLResource.java:71)
>        at
> org.xhtmlrenderer.swing.NaiveUserAgent.getXMLResource(NaiveUserAgent.java:212)
>        at
> org.xhtmlrenderer.pdf.ITextRenderer.loadDocument(ITextRenderer.java:137)
>        at
> org.xhtmlrenderer.pdf.ITextRenderer.setDocument(ITextRenderer.java:141)
>        at acts_as_flying_saucer.Xhtml2Pdf.main(Xhtml2Pdf.java:16)
> Caused by: javax.xml.transform.TransformerException:
> org.xml.sax.SAXParseException; lineNumber: 35; columnNumber: 169; The
> entity "nbsp" was referenced, but not declared.
>        at
> com.sun.org.apache.xalan.internal.xsltc.trax.TransformerImpl.transform(TransformerImpl.java:723)
>        at
> com.sun.org.apache.xalan.internal.xsltc.trax.TransformerImpl.transform(TransformerImpl.java:317)
>        at
> org.xhtmlrenderer.resource.XMLResource$XMLResourceBuilder.createXMLResource(XMLResource.java:189)
>        ... 5 more
> Caused by: org.xml.sax.SAXParseException; lineNumber: 35; columnNumber:
> 169; The entity "nbsp" was referenced, but not declared.
>        at
> com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1234)
>        at
> com.sun.org.apache.xalan.internal.xsltc.trax.TransformerImpl.transformIdentity(TransformerImpl.java:640)
>        at
> com.sun.org.apache.xalan.internal.xsltc.trax.TransformerImpl.transform(TransformerImpl.java:711)
>        ... 7 more
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/amardaxini/acts_as_flying_saucer/issues/4

## 

Thanks.
Amar Daxini

**Comment by ZinalMehta** [comment]
Hii @amardaxini ,
I am using version:9.0.7 but, still I got the same error mentioned by @kurianm 

![image](https://user-images.githubusercontent.com/41180275/77900527-cf33d780-729b-11ea-8f42-1670c5b99271.png)
